### ISSUE TITLE
Add preventDefault via touchstart on lightbox to prevent navigation swipe

### ISSUE THREAD

**Issue by Hirbod** [biati-digital/glightbox#146]
Currently, swiping on the edge of the iPhone will trigger a swipe/pop gesture to navigate back.
Since iOS 13.4 we can finally stop this from happening and the magic is just this:

```js
    /* Since iOS 13.4 we can prevent swipe back with preventDefault */
    const element = document.querySelector('.theLightBox');
    element.addEventListener('touchstart', (e) => {
      // is not near edge of view, exit
      if (e.pageX > 20 && e.pageX < window.innerWidth - 20) return;
      // prevent swipe to navigate back gesture
      e.preventDefault();
    });
```

Please consider adding this (replace element with the lightbox of course).

**Comment by biati-digital** [comment]
Great, i'll include it and push an update this weekend with some other bug fixes.

**Comment by biati-digital** [comment]
Added in the latest version 3.0.4

**Comment by biati-digital** [comment]
Latest version is now available on npm

**Comment by treeshuh** [comment]
Hi, I think this change made it links on slides don't work - for example, my slides are inline elements with links out to other resources, but now those links can't be clicked because of the prevent default. 

I rolled back to a previous version, but could you add this prevent default behind an option in a future update please?

**Comment by Hirbod** [comment]
This is true for android devices. I am investigating

**Comment by biati-digital** [comment]
This should be working on the latest version 3.0.7
