### ISSUE TITLE
Video from instagram not showing

### ISSUE THREAD

**Issue by wm-simon** [biati-digital/glightbox#171]
**Describe the bug**
Videos from instagram basic api are not playing.

**Are you able to reproduce the bug in the demo site**
Yes.

**To Reproduce**
1. Go to `https://bit.ly/35LySha`
2. Scroll down to `instagram section`
3. Click on this image:
![image](https://user-images.githubusercontent.com/3351449/99655382-f40fd180-2a5b-11eb-8504-c1b0fa3b0c66.png)
4. Endless loading icon is shown

**Expected behavior**
The video should be shown ;-) 
I think, the data-type is ignored.

**Post the code you are using**
Instagram basic api video url:
`https://video-frt3-1.cdninstagram.com/v/t50.2886-16/96842074_146950863538259_6278418427143941733_n.mp4?_nc_cat=106&vs=18142174291047602_3359975133&_nc_vs=HBksFQAYJEdGcXh4UVZUU0FXcXBvVUFBR1Z1TG9WTGJDRlhia1lMQUFBRhUAAsgBABUAGCRHS004d1FYSWpGcTFZcmdGQUtYaUlqeklLSFlLYmtZTEFBQUYVAgLIAQAoABgAGwGIB3VzZV9vaWwBMRUAACbk2Iq5w426QBUCKAJDMywXQDhMzMzMzM0YEmRhc2hfYmFzZWxpbmVfMV92MREAdeoHAA%3D%3D&ccb=2&_nc_sid=59939d&efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2RfdXJsZ2VuLjcyMC5mZWVkIn0%3D&_nc_ohc=h1BqNGgRUWgAX_FkTY5&_nc_ht=video-frt3-1.cdninstagram.com&oh=5bc04eecad7d9f06bbcc38c0fd6c7aa7&oe=5FDD89CC&_nc_rid=87d49f3e77`

HTML:
`<a class="link glightbox" href="https://video-frt3-1.cdninstagram.com/v/t50.2886-16/96842074_146950863538259_6278418427143941733_n.mp4?_nc_cat=106&amp;vs=18142174291047602_3359975133&amp;_nc_vs=HBksFQAYJEdGcXh4UVZUU0FXcXBvVUFBR1Z1TG9WTGJDRlhia1lMQUFBRhUAAsgBABUAGCRHS004d1FYSWpGcTFZcmdGQUtYaUlqeklLSFlLYmtZTEFBQUYVAgLIAQAoABgAGwGIB3VzZV9vaWwBMRUAACbk2Iq5w426QBUCKAJDMywXQDhMzMzMzM0YEmRhc2hfYmFzZWxpbmVfMV92MREAdeoHAA%3D%3D&amp;ccb=2&amp;_nc_sid=59939d&amp;efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2RfdXJsZ2VuLjcyMC5mZWVkIn0%3D&amp;_nc_ohc=h1BqNGgRUWgAX_FkTY5&amp;_nc_ht=video-frt3-1.cdninstagram.com&amp;oh=5bc04eecad7d9f06bbcc38c0fd6c7aa7&amp;oe=5FDD89CC&amp;_nc_rid=87d49f3e77" data-gallery="insta" data-description="<a target='_blank' href='https://www.instagram.com/p/CAIk1RxHvq7/' class='link__extern'><i class='fa-icon fab fa-instagram'></i> <i class='fa-icon fas fa-caret-right'></i> Post öffnen</a>" data-width="600" data-type="video">
                <img src="https://scontent-frt3-1.cdninstagram.com/v/t51.2885-15/96417359_147921236788942_1392607976219401296_n.jpg?_nc_cat=106&amp;ccb=2&amp;_nc_sid=8ae9d6&amp;_nc_ohc=0UQ-tijlh3wAX_x-sC1&amp;_nc_ht=scontent-frt3-1.cdninstagram.com&amp;oh=bda7af8dcff4bf03cf11bd865d0a85c2&amp;oe=5FDDA5F8">
            </a>`

**Screenshots**

**Desktop:**
 - OS: w10
 - chrome
 - 86

**Comment by biati-digital** [comment]
Hi @Pfeifakopf , your HTML it's not correct, you can not add HTML inside an attribute, please checkout the README and adjust your code. Also the data type video it's only for the supported platforms: youtube, vimeo and self hosted, you need to set it as an iframe

**Comment by Pfeifakopf** [comment]
@biati-digital Thanks for your fast answer! I removed the inside html and changed the data type to iframe, but it is still not working.

**Comment by biati-digital** [comment]
Hi, sorry for the delay, my bad, you should set the data-type to "external" not iframe

**Comment by sayontan** [comment]
I tried out the suggestion here - it doesn't seem to work. Specifically in case of the markup above (after removing the HTML attributes) if you set data-type to external, it seems to ignore the fact that you have a video altogether.

I did notice that your code is flexible enough to load external (non-local) videos as long as the files have a valid extension such as mov, mp4, ogg or webm. That is why, I can have an `a` tag in my page pointing to an mp4 file on SmugMug, and GLightbox will still play the video without any issue.

In looking through the code, it looks like there is a bit of a problem in the `slideVideo` function. You have individual `if` conditions checking for YouTube, Vimeo and for file extensions. The file extension checker says:

```
if (url.match(/\.(mp4|ogg|webm|mov)$/) !== null) {
```

This is explicitly checking for a URL _ending_ in one of the above extensions, but in case of the original post, there are additional parameters after ".mp4", which is causing the match to fail. Instead, if you rely on the JS URL object (by passing the url to `new URL()`), you will be able to retrieve the true file name using the `pathname` attribute of the URL object.

So, the code becomes something like this:

```
var urlObj = new URL(url);
if (urlObj.pathname.toLowerCase().match(/\.(mp4|ogg|webm|mov)$/) !== null) {
```

Subsequently, inside the code you have a check to try and obtain a file extension:
```
var format = url.toLowerCase().split('.').pop();
```

Here too you can use the `pathname` .

One other issue that I noticed (unrelated to the OP's post) is that even if you use `data-type="video"`, if you pass a link that does not have one of your supported extensions (e.g. a video from Flickr, or from Google Photos), it will fail your checks and not load in the lightbox (because you are explicitly looking for an extension). I fixed this at my end by passing a `data-format="mp4"` in the element, and modifying the condition to determine the `format` by first checking for the `data-format` attribute.

Sorry, I am not very familiar with the process of pull requests, otherwise I would have submitted a patch for this. As I have written in a different topic, I was integrating this script into a WordPress plugin that I have, and I have made these edits over there.

**Comment by biati-digital** [comment]
Hi @sayontan URL object is not supported by internet explorer that's why it's not used, as stated in the README, video support is Vimeo, Youtube and local video as that are the sources that Plyr supports. I'll rather offer a way for developers to pass a custom function to detect the source type.

**Comment by sayontan** [comment]
Ah, I thought you were using polyfills, but now I can see that you are not.

In any case, I need to support videos without extensions, so, pending an update from your end, I will keep my code (or a polyfill variant of the `pathname` by first separating the url on "?"). That will let my code work with the script.

Strictly speaking, Plyr doesn't talk about "local" videos explicitly - it supports any video that you pass in the `src` attribute of the `source` element within a `video` node, and it does not need the URL to have a specific set of extensions, though it seems to need the MIME type. You can use Plyr with a video from Google Videos as long as you are passing the `type` attribute to it.

**Comment by biati-digital** [comment]
Yes, some future update (v4) will drop support for IE and maybe offer another version with polyfills, still deciding.

I'm aware of the video source, but this is exactly why i said only local videos, there are hundreds of services to store video. If someone uses a specific service and the video it's not displayed guess who they're gonna ask for support.

I'll take a look at this for sure, it would be great to support more video sources and it's seems to require only some minor changes.

**Comment by biati-digital** [comment]
Closing this as there were no more replies from the original issue. Again, this is something that i'll try to implement in a future update.
