### ISSUE TITLE
Add a counter

### ISSUE THREAD

**Issue by AndrianD** [biati-digital/glightbox#201]
It's a great project, thank you very much! However I was thinking to myself, would there be a way to add a **counter** when browsing an image gallery for example? Something similar to 1 of 3, 2 of 3, 3 of 3, you know what I mean?
Well done anyway, it's a great job!

**Comment by biati-digital** [comment]
Hi @AndrianD glad you like it. There's no plans to add a counter for now but there was and old issue about this #69 so maybe it can give you an idead about how to implement it. Since that issue the API has changed so you'll have to modify it. I'm not able to help with this as I'm really busy but if you need help you'll probably have luck in stackoverflow.
