### ISSUE TITLE
Lightbox and Plyr do not work when Require.js is present on the page

### ISSUE THREAD

**Issue by Lefthandmedia** [biati-digital/glightbox#207]
**Describe the bug**
When the page also has **Require.js** , Glightbox and Plyr do not work anymore.
We have Glightbox bundled in our app with webpack. But for legacy reasons require.js is also loaded on the page.
None of the modules in our project seem to mind except Glightbox

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
- Add `<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js"></script>` before loading dist/js/glightbox.js
- look at the page

**Expected behavior**
I expect Glightbox to work

**Desktop:**
All

**Smartphone:**
All

**Comment by frankie-tech** [comment]
Does PLYR load without GLightbox?

If it does, I *think* you can just pass an empty string to `settings.plyr.js` and `settings.plyr.css` respectively in the settings object. It wouldn't be a solution, but it *might* at least get it to show up?

**Comment by WilsonNet** [comment]
@frankie-tech solution worked, I loaded plyr from a cdn and passed empty strings and now it's working.

**Comment by frankie-tech** [comment]
@WilsonNet Glad to hear it!

**Comment by Lefthandmedia** [comment]
@frankie-tech I wouldn't know because we don't use Plyr. except through Glightbox of course.

**Comment by frankie-tech** [comment]
@Lefthandmedia Right, you still need the code in your project somewhere. I'm suggesting rather than relying on GLightbox to load plyr as a dependency you use another method.

If you're loading GLightbox with require.js, use that. If you're bundling GLightbox with something like Webpack, add plyr as a dependency and import it manually. Then disable the CDN loading plyr in by passing in those strings in the GLightbox settings object.

Hopefully I've explained my monkey-patch a little better this time 😊

**Comment by Lefthandmedia** [comment]
@frankie-tech You're totaly right. I have a script that initialises Glightbox. I start that script now with. On top of leaving the `settings.plyr.js = ''`

```
import Plyr from 'plyr';
window.Plyr = Plyr;
```
And it works thanks a lot

**Comment by frankie-tech** [comment]
No problem! Glad it worked out 😊
