### ISSUE TITLE
Module import does not work as described in the README

### ISSUE THREAD

**Issue by yujiri8** [biati-digital/glightbox#212]
**Describe the bug**
Importing glightbox as shown in the README does not work.

**Are you able to reproduce the bug in the demo site**
No

**To Reproduce**
Steps to reproduce the behavior (original context, unsimplified):
1. Have `import GLightbox from 'glightbox';` at the top of a JS module which is bundled by rollup.
2. Build it.
3. Compilation error: `[!] Error: 'default' is not exported by node_modules/glightbox/dist/js/glightbox.min.js`

Can also reproduce in a simplified environment: an HTML page with the following:
```html
<script type="module">
import GLightbox from 'https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.js';
</script>
```
1. Load page
2. See console error: `Uncaught SyntaxError: import not found: default`

It works if I just do `import 'https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.js'`, without the `  GLightbox from  `.

**Expected behavior**
Either of these examples work, since they are suggested in the README.

**Desktop:**
 - OS: Linux
 - Browser: Firefox
 - Version: 86

**Comment by frankie-tech** [comment]
Since GLightbox has a UMD wrapper and not an ESM standard `export default` or `export { GLightbox }`, it makes sense that that wouldn't work.

But as you found out, just importing the JS file will work as this still runs the code inside the file. A short explainer [here](https://gomakethings.com/side-effects-in-es-modules-with-vanilla-js/).

Can you confirm `import 'glightbox';` works inside of the bundler?

**Comment by yujiri8** [comment]
> Can you confirm `import 'glightbox';` works inside of the bundler?

Yes.

The issue is why is `import GLightbox from 'glightbox';` in the README if it doesn't work?

**Comment by frankie-tech** [comment]
Not sure 🙂 Couple reasons I can think of are:

<details>
<summary>Got lost in transpilation</summary>

Since GLightbox in the `dist/` is UMD wrapped, there isn't an `export default` statement.

Look inside `src/` though, and at the bottom of the page is the necessary `export default`.

This is because, as far as I know, UMD hasn't updated their definition to work with ESM yet.

Hopefully they do soon. Probably won't though...
</details>

<details>
<summary>Babel got screwy</summary>

It's possible that at one point there was a UMD and ESM version.

Then using the `package.json`, the bundler would know to use the ESM version instead of the UMD version.
</details>

<details>
<summary>It's just a documentation error.</summary>

GLightbox is maintained by one person as a side project.

It happens 🙂 
</details>

The solution for the meantime, for others looking to import GLightbox as a module/inside a `type="module"` script tag, is to import it like this:

```js
import '/file/path/or/link/to/glightbox.js';

const lightbox = GLightbox({ ...options });
```

This will load GLightbox using the UMD wrapper method, meaning it's now available on the `window` object.
