### ISSUE TITLE
trigger or invoke the image gallery from a button

### ISSUE THREAD

**Issue by DTHerrera** [biati-digital/glightbox#219]
Is it possible that you can invoke or launch the image gallery from a button?

what I mean is that on my page there will be a button that when the user clicks the image gallery is displayed.

Thanks a lot.
![button](https://user-images.githubusercontent.com/36610780/112085083-c78ed200-8b81-11eb-89b7-f1c1a343e5d2.JPG)

**Comment by biati-digital** [comment]
Hi @DTHerrera, if you need help please post it on stackoverflow. this is only for issues related to the library or feature requests.

**Comment by ronilaukkarinen** [comment]
@biati-digital This is actually a legit question and in my opinion part of this repository. Pointing to Stack Overflow is just rude.

I have spent a better part of the hour by looking for a way to use it like `<button type="button" data-trigger="https://vimeo.com/1084537">Trigger video modal</button>` but haven't yet found any built-in way to do that. Is there? It seems glightbox depends on a link element `<a href="">` where `href` is the target. There is no documentation how to create trigger of other elements like button or even div if one likes to. Please give even some tips. Thanks!

**Comment by Niq1982** [comment]
@DTHerrera @ronilaukkarinen 
This is kind of explained in the documentation. You can always set up the elements in the lightbox settings object rather than using `<a href="..` elements. Like this:
```
const myGallery = GLightbox({
    elements: [
        {
            'href': 'https://picsum.photos/1200/800',
            'type': 'image',
            'title': 'My Title',
            'description': 'Example',
        },
        {
            'href': 'https://picsum.photos/1200/800',
            'type': 'image'
        },
        {
            'href': 'https://www.youtube.com/watch?v=Ga6RYejo6Hk',
            'type': 'video',
            'source': 'youtube', //vimeo, youtube or local
            'width': 900,
        },
    ],
});
```
After this you just have to set up the button to trigger `myGallery.open();`

Here's a working example you can tinker with: https://codepen.io/niq1982/pen/PoWgVQK

**Comment by DTHerrera** [comment]
I am very grateful for the support, thank you for setting an example of how to use this great tool. I'm very useful this solution

best regards

**Comment by biati-digital** [comment]
@ronilaukkarinen for me what what's really rude was the people who started going through our website and sending us messages expecting us to send them examples of how to do something or modify GLightbox to fit their needs. They started sending WhatsApp messages and when somebody actually called us about GLightbox It was too much. I decided to automatically close all the issues with questions about "how do I do something" and send them to stackoverflow. After that we never received another email about this. I do not want to be in that position again.

I always wanted to help just take a look at this issue #89 but GLightbox it's for people that are not new to coding or feel confortable with Javascript, like @Niq1982 explained, you can learn how to do it in the docs, it's right there.

Issues like these can stay open months because if I do not reply or @frankie-tech there's a really small chance that another person jumps in and helps but when it happens I really appreciate it @Niq1982 

Having said that, we are planning to create examples for questions like this so people have a way to find it quickly and restructure the docs.

**Comment by ronilaukkarinen** [comment]
Encountered a project that needs this on a `<button>` element and searched for my old replies.

For future self and other help seekers:

``` html
<button data-gallery="hero-video" class="open-video-fullscreen no-external-link-indicator play-video" type="button" data-video-url="https://player.vimeo.com/video/327180404?background=1&autoplay=1&loop=1&byline=0&title=0">
  Play video
</button>
```

``` js
if (document.querySelector('.open-video-fullscreen')) {
  const videoButtonSelector = document.querySelector('.open-video-fullscreen');
  const dataAttribute = videoButtonSelector.getAttribute('data-video-url');

  const lightbox = new GLightbox({
    elements: [
      {
        type: 'video',
        source: 'vimeo',
        autoplayVideos: true,
        href: dataAttribute,
        openEffect: 'none',
        closeEffect: 'fade',
        cssEfects: {
          fade: { in: 'fadeIn', out: 'fadeOut' },
          zoom: { in: 'zoomIn', out: 'zoomOut' },
        },
        touchNavigation: true,
        loop: false,
        plyr: {
          config: {
            ratio: '16:9', // or '4:3'
            muted: false,
            youtube: {
              noCookie: true,
              rel: 0,
              showinfo: 0,
              iv_load_policy: 3,
            },
            vimeo: {
              controls: false,
              autoplay: true,
              background: false,
              loop: false,
              byline: false,
              portrait: false,
              title: false,
              speed: true,
              transparent: false,
            },
          },
        },
      },
    ],
  });

  videoButtonSelector.addEventListener('click', (event) => {
    lightbox.open();
  });
}
```
