### ISSUE TITLE
Upscale image to fill browser window.

### ISSUE THREAD

**Issue by warrenkc** [biati-digital/glightbox#223]
See example code: [https://codepen.io/warrenkc/full/LYxGoOX]

I want to be able to make any image fill the browser screen using the maximum size possible while not changing the ratio or cropping the image. When I set the width or height in the JavaScript options, it doesn't seem to have any effect.

Is there a way to do what I am describing?

Thank you!

**Comment by frankie-tech** [comment]
Sorry, there isn't a way to do that. Zoom function takes an image that should go out of bounds instead fit the bounds, and then zoom out on click. Your best bet is to use larger images, or to write your own event listener and manipulate the image from there. 

Since this isn't a feature request or a bug report, I'm going to close this issue. See our support guidelines [here](https://github.com/biati-digital/glightbox#support).
