### ISSUE TITLE
Set varied video widths

### ISSUE THREAD

**Issue by stfullstack** [biati-digital/glightbox#246]
I have a portfolio of videos I'd like to display in a gallery.

Each video has different ratios and dimensions. It is being hosted on Vimeo.

I have been spending some time trying to get the library to display the correct dimensions for the video but it always only ever displays the one dimension.

**Comment by frankie-tech** [comment]
Hey there @stfullstack,

All the video and iframe player elements are controlled by plyr.js library.

We expose all of their settings and the Plyr object for each individual slide, but if you're having issues, you should check out the issues in their repo.

Maybe #196 can also be some use to you?

Since this isn't a bug or a feature request, I'm going to close this issue. See our support policy [here](https://github.com/biati-digital/glightbox#support).
