### ISSUE TITLE
Duplicated id's in inline content forms

### ISSUE THREAD

**Issue by kimchristiansen** [biati-digital/glightbox#247]
If you link to an inline content element as a lightbox, this element will be copied. This has the consequence that ID's are duplicated. For example, if you use a form with input fields as inline content, it will conflict with the duplicated input fields. Labels that are assigned to input fields can no longer find "their" input field when clicked.

Here is an example with a checkbox. 

https://jsfiddle.net/ths02qkf/

The label of the original checkbox changes the state of the corresponding checkbox. The checkbox label in the lightbox no longer changes the state of the checkbox, because it now has two checkboxes with the same ID.

Is there a way to remove the original element when it is opened in the lightbox? Of course it would have to be added back when the lightbox is closed again. Or are there other ways to fix this problem?

**Comment by kimchristiansen** [comment]
As a workaround, I copied the HTML from the inline content and deleted the node from the dom.

Here is the example:
https://jsfiddle.net/2hdf38mx/2/

**Comment by frankie-tech** [comment]
Hey @kimchristiansen,

This is a really tricky one, and one that it would be hard to find the answer to organically.

I do want to say up front, we don't normally offer support outside of feature request and bug reports, see [here](https://github.com/biati-digital/glightbox#support).

Since the `label` `input` relationship is so important though, we'll call it documentation 😉 

If it were me, there are two paths I would take, and then it is up to your comfort level which you would want to do. _Full disclosure: I'm replying from my phone, so these aren't going to be copy paste solutions._

First one would be to take your form or inline content, and put it inside of a `<template>` element. The `<template>` element contains the form inside of a `DocumentFragment` which isolates the HTML. This should prevent any issues with duplicate IDs and inputs no longer connecting to the right input in the form. You can read up on it more [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template).

Make sure that the element for inline content that GLightbox is given is the one inside of the template element. If you pass in the template element, it will not show anything as templates hide their content by default.

The other would be to set the slide element when you create your lightbox with JavaScript.

Using the `elements` option in the GLightbox config object, make an array, and add an object with the key "content" and your inline element as a template literal `` ` ``.

```js
const lightbox = GLightbox({
  elements: [
    {
      "content": `
      <!-- your inline content -->
      `
    }
  ]
});
```

Then rather than copying HTML from the DOM it will use that template literal instead.

**Comment by kimchristiansen** [comment]
Thanks for the quick answer - and of course for the cool lighbox library! That's quite a few possibilities then.
I have entered it as an issue in case others encounter the same issue.
