### ISSUE TITLE
how can I get an id to show on the image?

### ISSUE THREAD

**Issue by starchild** [biati-digital/glightbox#263]
We have the need to assign a custom ID to each large gallery image.  How can we achieve this by adding perhaps

data-id="something" 

on the thumbnail image ?

Thank you,

**Comment by frankie-tech** [comment]
Hey there @starchild,

There are a couple of ways you can solve this.

Since it sounds like you need to add it using HTML data-* attributes, then I suggest looking at the callbacks like `open` and `slide_changed`.

The original GLightbox that is initialized has an `elements` key, that contains the current slides and probably all the info you need to roll something together yourself 😊 

Hope this helps!
