### ISSUE TITLE
missing playsinline

### ISSUE THREAD

**Issue by Sodah73** [biati-digital/glightbox#267]
On iOS the video will playing not in the Popup. In your code i found:  webkit-playsinline.
But this will not work. You need this: playsinline

Look at here:
https://css-tricks.com/what-does-playsinline-mean-in-web-video/

**Comment by frankie-tech** [comment]
Hey there @Sodah73,

Didn't realize they had deprecated that. Looks like just a line of HTML that needs to be added [here](https://github.com/biati-digital/glightbox/blob/master/src/js/slides/video.js#L53-L60).

If you're up for making a PR, I say checkout our [contributing guide] and go for it. Otherwise it's open for anyone to take a crack at.

**Comment by biati-digital** [comment]
This is fixed in the latest version 3.1.0
