### ISSUE TITLE
Attempted to assign to readonly property

### ISSUE THREAD

**Issue by bpruneau** [biati-digital/glightbox#269]
![image](https://user-images.githubusercontent.com/1107683/126173963-65bd8c2c-bc08-4b60-bbe6-fadb530435c4.png)

**Comment by frankie-tech** [comment]
Hey there @bpruneau

Please submit this again using one of the provided issue templates.

Submitting just a screenshot of an error tells us nothing about the issue that you are having. We are not coding in the same environment that you are and have no context.

Please keep that in mind.

Closing due to lack of information.
