### ISSUE TITLE
plyr does not work in modal if a different plyr element is instantiated elsewhere

### ISSUE THREAD

**Issue by joshua-martin** [biati-digital/glightbox#270]
I have a video that is embedded directly on my templates as well as having videos that appear in a glightbox modal. I am loading plyr via CDN directly on my templates.

**Direct init**
```
<div class="plyr__video-embed opacity-0" id="homepage-watch">
    <iframe src="{{ ... }}?origin=https://plyr.io&amp;iv_load_policy=3&amp;modestbranding=1&amp;playsinline=1&amp;showinfo=0&amp;rel=0&amp;enablejsapi=1" allowfullscreen allowtransparency allow="autoplay"></iframe>
</div>

new Plyr('#homepage-watch')
```

**Modal init**
```
<a href="https://www.youtube.com/watch?v=XXX" class="glightbox-video">
    <img src="{{ ... }}"  />
</a>

GLightbox({
    selector: '.glightbox-video',
    touchNavigation: true,
    type: 'video',
    source: 'youtube',
})
```
If I insantiate the `homepage-watch` Plyr element, none of the elements work in the modal–it just spins forever. If I remove the init on the element, then the modal videos work fine.

https://user-images.githubusercontent.com/1694957/126341886-091a3400-7a23-4024-9c51-2310d042005f.mov

**Comment by frankie-tech** [comment]
Hey there @joshua-martin,

A couple of things:

First, the `type` and `source` properties are only necessary if you are adding slides using `elements: [...]` or one of GLightbox's methods.


Secondly, GLightbox adds a script tag with a cdn for PLYR.js, which *might* be causing a side effect. 

You can find an example of how to disable it here #207

Lemme know if either of those don't work.

**Comment by biati-digital** [comment]
GLightbox only adds PLYR.js when necessary. If your site already loads Plyr, GLightbox will not append the script. Anyway without more information or examples it's really difficult to know what's happening.

**Comment by frankie-tech** [comment]
Whoops, totally missed that when I was reading through the code earlier.

**Comment by joshua-martin** [comment]
I'm not really sure there is too much more info I can give. As per the provided video, I instantiate Plyr on an element that isn't in a lightbox, it stops the lightbox Plyr init scripts from working.

I've set up a basic demo. You can see that the lightbox videos do not show when you click on them, but if you remove the `new Plyr` instance, they do. https://codepen.io/jsmrtn/pen/ExmvrZZ

**Comment by biati-digital** [comment]
@joshua-martin when you create an issue there's more info you can provide for example: 

- What browser and version are you using? 
- GLightbox version
- Plyr version
- Are you using a build tools like webpack, gulp, etc? 

We don't know anything about your development environment, there has been some posted issues that were caused by  a CSS minifier and again, we don't know this because the user simply decided to skip that part. This information can help us to find errors faster, i appreciate the video but we can only see that there's an error and that's it. We currently do not have the time to try to replicate the error that's why we ask for a live example. Having said that, thank's for the demo site.

**Comment by joshua-martin** [comment]
@biati-digital Sure–apologies I hadn't mean to be terse. I did say I was pulling from the direct from the CDN, but had thought I had included the versions.  Appreciate your work on GLightbox–it's a plugin we use on most of our sites.

**Comment by robbiegod** [comment]
I hope I am not disrupting here, but I have a related question to this topic. 

Since GLightbox uses Plyr, I am going to switch my website to use Plyr too.  I am currently using MediaElement.  Should I load Plyr before or after GLightbox since I'll be loading it outside of GLightbox.  I think before so GLightbox can access it.  Do I need to pass any parameter to GLightbox to tell it not to load Plyr?

**Comment by frankie-tech** [comment]
@robbiegod GLightbox only adds a script tag with a src to a CDN if PLYR isn't found in the global object (`window`), otherwise it just uses the PLYR that already exists.

**Comment by biati-digital** [comment]
@robbiegod the order does not really matter, GLightbox will only inject Plyr when the lightbox is opened and only if there's a video slide.

Unless you're opening a lightbox on page load, in that case add Plyr before.

**Comment by biati-digital** [comment]
@joshua-martin no problem, if you check the file in CDN that you are using it's a previous version 3.0.8 don't know why. 

Anyway, this seems to be happening only with youtube videos, copy/pasted the code to replicate the issue and if i change the video (from the first 500x500 box)  to vimeo or self hosted it works correctly. 

Not sure this is related to GLightbox, in this specific case Plyr never triggers the ready event for the youtube video but it's triggered correctly for vimeo and self hosted.

This requires more testing but currently i do not have the necessary time to do this so any help is appreciated.

**Comment by Androlax2** [comment]
Had the same issue with Youtube video but not others !
