### ISSUE TITLE
Custom Close Button from within an inline / iframe element

### ISSUE THREAD

**Issue by carstengrimm** [biati-digital/glightbox#284]
I'm using the glightbox to call an url as inline/iframe element, whereas there is an AJAX script to load an infinity scroll gallery, at the end of the AJAX call when there are no new objects i am planning to provide a button at the bottom of the html document which should act as a method to close the glightbox-modal but i am not sure if it's accessible and had no working result so far.

The init of the inline is pretty much default

```
    <div class="text-center">
        <a href="<?= $data->url() ?>" class="glightbox px-4 py-2 bg-primary-500 hover:bg-primary-700 text-white rounded">
            <?= $data->button() ?>
        </a>
    </div>
<script>
    var glightbox = GLightbox({
      selector: '.glightbox'
    });
</script>
```

Where as the called url consists out of a php script with full html, head, body.

![image](https://user-images.githubusercontent.com/5014509/131214533-dce8c9d7-c877-4220-a5c4-af5023aa3b68.png)

**Comment by frankie-tech** [comment]
Hey @carstengrimm,

If I understand this correctly, you are trying close a GLightbox instance from inside of an `iframe`?

Like this:
```html
<glightbox html>
  <!-- slide with iframe -->
    <iframe>
      <!-- close button -->
```

If that's the case, you can't use JS to reach out of the `iframe` .

There may be a way to send messages between the `iframe` and the owner document using `window.postMessage`.

We only support bugs and feature requests, so that is something you would need to test on your own.

**Comment by carstengrimm** [comment]
thanks for the response. will think about it. however i may just leave it with the default button as well as clicking anywhere else ... not sure if the window.postMessage function could potentially enable CORS attacks or be a security issue. My thought was, that there could've been a function already build in. No problem.
