### ISSUE TITLE
Weird flash on lightbox on iPad

### ISSUE THREAD

**Issue by gregoirenoyelle** [biati-digital/glightbox#302]
**Describe the bug**
There is weird flash on image or video when displaying or quit the lightbox

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Go to https://biati-digital.github.io/glightbox/ with Safari on iPad
2. Click on image or video
3. Click on cross for closing

**Expected behavior**
More fluid effect. 

**Post the code you are using**
Same problem on demo site or in my website. 

**Screenshots**
Here is a [videos capture from my iPad (hosted in DropBox)](https://www.dropbox.com/s/a77n1ggoxwk79n3/ipad-pro-bug-ios-14_8.mov?raw=1).

**Smartphone:**
 - Device: iPad Pro 10.5 pouces
 - OS: 14.8.1
 - Browser: Safari.
 - On the same iPad, no problem at all on **Firefox** or **Google Chrome** app. That’s strange. 

Thanks !

**Comment by frankie-tech** [comment]
Hey @gregoirenoyelle,

I tested it out on an physical iPad I have here and wasn't able to produce the issue.

But the fact that you weren't able to get it on the iOS Firefox or Google Chrome app is really odd. Since Safari is Safari, does this happen if that is the only window/tab in Safari you have open? I'm wondering if there is something in a background tab that may have been sucking up some of the rendering performance. 

The only other thing I can think of is some weird quirk of some CSS property.

**Comment by gregoirenoyelle** [comment]
Hey @frankie-tech 
I think you’re right. I just restart the iPad and everything works fine. 
Thanks for your support !
