### ISSUE TITLE
Image with Dynamic Parameters?

### ISSUE THREAD

**Issue by bornResponsive** [biati-digital/glightbox#307]
Is it possible to work with CDN images that have dynamic parameters to control the size and quality?

For example, when testing with Unsplash image URL, it produces shrunk image with white background. 

_The below image is 1200 x 1927 pixels._
<img width="918" alt="Screenshot 2021-12-22 at 11 31 04" src="https://user-images.githubusercontent.com/4182478/147086546-5b9efa03-4d03-43fb-b938-0225489a5831.png">

Also with another CDN, and you get similar issues with landscape image. 

_The below image is 2200x1466 pixels._
<img width="934" alt="Screenshot 2021-12-22 at 11 36 45" src="https://user-images.githubusercontent.com/4182478/147086999-448b96a4-eb20-4c5b-9b5f-b103312bb6b7.png">

Essentially, I want the same behavior as the demo site where the background is black and centered.
Am I doing something wrong or is there a way around it?

Many thanks.

**Comment by frankie-tech** [comment]
hey there @bornResponsive 

Two things, we can't get a good understanding of what is happening with your code without *seeing* your code. A codepen or codesandbox goes a long way when helping us understand and debug what is happening.

Secondly, we don't help with support issues.

Due to time constraints on both the maintainer and I, we're only able to handle bug reports and feature requests. 

*That being said...* This sounds like it could be a CSS issue, like adding `object-fit: cover` or `width: 100%`. 

It could also be an Unsplash issue, is there a parameter to add to the url to crop the image rather than maintaining the aspect ratio? Maybe that is the max width of the image?

There are too many factors that are not GLightbox. If you can check out those suggestions first, reproduce this in a CodePen, I can take a quick look at it in case it is a bug.

**Comment by biati-digital** [comment]
hi @bornResponsive try data-type="image", (please take a look at the docs).  You are seeing that error because GLighbox can not understand what type of URL you are adding so it defaults to iframe (That's my guess as you did not post any code), you need to specify that it's an image using **data-type**

**Comment by bornResponsive** [comment]
Hi @frankie-tech @biati-digital, thanks for the suggestion. Adding the data-type did the trick. 

Basically, I downloaded the demo page and replaced the images with CDN images without thinking about applying the data type. 

Thanks for your amazing work and support.

**Comment by Sennik** [comment]
> hi @bornResponsive try data-type="image", (please take a look at the docs). You are seeing that error because GLighbox can not understand what type of URL you are adding so it defaults to iframe (That's my guess as you did not post any code), you need to specify that it's an image using **data-type**

I had the same issue with links produced by [Glide](https://bumptech.github.io/glide/doc/getting-started.html#basic-usage) which I am using as part of Statamic. adding data-type="image" to the href solved my problem too :-)
