### ISSUE TITLE
Hls m3u8 videos playback

### ISSUE THREAD

**Issue by joural** [biati-digital/glightbox#312]
Hi there, so while implementing glightbox to my website it occurred that I should provide my video content in various quality. 
The feature to provide video content in different quality is widespread and used daily by likes of youtube, vimeo and other video hosting services, not every user has lightning speed broadband at their disposal and adjusting video bandwidth requirements would make for better user experience. Hence I was wondering about playback of such m3u8 files in glightbox, I found standalone plyr solution on [Plyr + HLS.js & video quality Matthew Marino](https://codepen.io/karnith/pen/MWoyaGR) but getting it to work with glightbox is pretty challenging.
Thank you

**Comment by frankie-tech** [comment]
Hey there @joural,

First off, please use the provided templates when submitting issues. This helps us organize issues, and deal with them faster. The templates also require code examples, which help us immensely 🙂 

Since I don't have an example to work off of, and we don't offer support for implementation, I can't help much here. I can only point you in the direction of trying to use a different slide type. I'm going to guess that the slide that is being generated is a video slide, I would suggest try and see if an inline slide would work better. 

If you checkout the [demo](https://biati-digital.github.io/glightbox/), scroll down to the section with the heading "Iframes and Inline Elements" and click on the first slide, you can get an idea of what to do.

Hope that gives you some direction.

Closing issue due to missing template and code examples.
