### ISSUE TITLE
Zoom on mobile issue

### ISSUE THREAD

**Issue by X-Tender** [biati-digital/glightbox#315]
**Describe the bug**
I have experienced on mobile the problem that the pinch zoom only works when you didnt touch the image. You have to touch the black surrounding and then zoom in. after that you can touch the image to pinch/zoom.

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Go to https://biati-digital.github.io/glightbox/ on mobile
2. Click on first image with women
3. Try to zoom/pinch by touching the image.
4. Didnt work
5. try it by zooming/pinhcing the surrounding
6. Works

**Expected behavior**
When I pinch/zoom the image it should zoom too.

**Smartphone:**
 - Device: Pixel4XL
 - OS: Android 11
 - Browser chrome
 - Version latest

**Comment by end2endi** [comment]
I experienced the same problem on my phone (Galaxy S8+). Once you pinch to zoom outside of the image, it appears to enable pinch to zoom on the image.

Smartphone:

    Device: Galaxy S8+
    OS: Android 9
    Browser: Chrome
    Version: Latest

**Comment by biati-digital** [comment]
i'm not able to replicate this error on an iPhone 11 with Safari, Edge or Chrome, seems the problem is specific to Android devices. I do not own an Android device so any help is appreciated.

**Comment by Tof63** [comment]
Good evening
I use a translator. 
A website editor has been using your plugin recently and I told him that I also have huge problems zooming an image on a touch screen using my fingers. 
I read this topic and it is very similar to my problem.
I have the problem on 2 Samsung / Android 11 devices.
It's a shame you can't test Android but I think it would be a good thing as I think Samsung and Android are 2 big players in the digital world
I'm sorry I can't help you more.
Another remark is that when you zoom in on a smartphone, you have to unzoom in order to move to the next image. It's not practical at all because you end up in the black frame of the image and you don't know what to do. 
Thank you for your work
Best regards

Translated with www.DeepL.com/Translator (free version)

**Comment by wzol** [comment]
Can replicate the issue: use Dev console, and with shift+left mouse click you can simulate pinch on mobile view. Can't zoom images.

**Comment by zehawki** [comment]
Pinch zoom is extremely fussy and makes it unusable. As @X-Tender mentioned, it sometimes (but not always) works when the zoom motion is performed on the black surrounding. Sometimes the zoom doesnt happen and the upon swiping, the next or previous image shows zoomed.
