### ISSUE TITLE
Usercentrics cookie consent script prevents lightbox from showing any content, just a spinning wheel

### ISSUE THREAD

**Issue by Anguel** [biati-digital/glightbox#342]
While cookie consent has not been given for Youtube/Vimeo videos the Usercentrics script normally displays a consent dialog over the video where the user has to accept cookies in order to play the video. This is strictly required by GDPR/DSGVO.
Now, when the video opens in Glightbox unfortunately the user only sees a spinning wheel forever on the dark background and no video and no consent dialog are shown. When I click again to close the lightbox, in a couple of milliseconds, while the box closes I can see that there is the consent dialog over the video that did not show.
Any ideas for a quick workaround? I tried disabling autoplay but this did not change anything.

**Comment by gingerchew** [comment]
Sorry @Anguel,

We don't offer help for these types of issues. Due to the time constraints of both the owner and I, we limit it to bug reports and feature requests.

If I had to take a guess, sounds like a `z-index` issue. 

I also recommend looking in the Plyr repo's issues to see if someone has had similar problems. Plyr is the video library that is used inside of GLightbox.

**Comment by biati-digital** [comment]
This might be more related to Plyr, GLightbox only initializes the player and waits for Plyr to notify it's state, if you only see the spinning wheel that means that Plyr does not notify it's state, probably because the other script is blocking it?
