### ISSUE TITLE
Issue with lightbox.close(); ?

### ISSUE THREAD

**Issue by mattrudd2020** [biati-digital/glightbox#344]
GREAT script here, thanks! 

Forgive me if this isn't a bug and my error, but I've been struggling with this for hours!

I'm wanting to click anywhere in the open lightbox to close it. The default 'closeOnOutsideClick' option isn't suficient, as I'm running my video at 100vw.

I've tried:

$( '.gLightbox-container').on('click', function(event) {
     lightbox.close();
});

Also tried a solution on [Stackflow](https://stackoverflow.com/questions/49327148/close-glightbox-gallery-by-clicking-outside-content-area) with an Eventlistener solution that doens't seem to work any more

With this jquery I expected a click anywhere in the open container to trigger the lightbox close function.

Sure it's that I'm doing something wrong?

Codepen: https://codepen.io/matt-rudd/pen/qBoVjVN

Many thanks!

**Comment by biati-digital** [comment]
This is not a bug, it's simply that your code is not correct, we are unable to provide support for this type of cases, only bugs and feature requests.

Just to give you a hint, your code does not work because you are not clicking the container, the video is above and that's what you are clicking. You have a button called EXIT that follows the mouse everywhere, why don't you set the event listener to that button (remove the pointer-events: none; to be able to click it)? 

Anyway, hope you can find a solution.
