### ISSUE TITLE
2.0.2 html description

### ISSUE THREAD

**Issue by carstengrimm** [biati-digital/glightbox#58]
after updating to 2.0.2 it does not seem that html description work. 

on previous versions as well as the previous docs it was stated that html inside descriptions are working, however without doing changes to my glightbox  but just updating broke it.

**Comment by biati-digital** [comment]
That's weird, i didn't change the descriptions in the demo site or in the code, they work correctly in the demo.

Can you share how are you adding the descriptions?

**Comment by carstengrimm** [comment]
The html output is: 

```
              <a href="https://link-to-file.jpg" class="glightbox" data-glightbox="title: <a href='https://some-url' class='button is-primary'  style='display: block; margin-left: auto; margin-right: auto; width: 20em;'><i class='fa fa-cart-plus'></i> Some Linktext</a>; descPosition: bottom;">
```

**Comment by biati-digital** [comment]
Is that the final output? 

Just a few things, if you are planning to add the link in the data attribute your html has to be encoded, the code you posted is not valid html, changing the double quotes to single is not enough.

Example of html link encoded.

`
data-glightbox="title:Description Bottom; description: You can set the position of the description &lt;a href=&quot;http://google.com&quot;&gt;Google&lt;/a&gt;"
`

Already tried the code above and it works.

You are also adding the html link in the title attribute not the description, the description parameter is processed differently to other parameters.

Instead of adding the html in the data parameter you could try the other method, adding a div with the class of glightbox-desc to append your html, this way you don't have to encode the html.

**Comment by carstengrimm** [comment]
woops, sorry i posted the wrong code here...

in my final code it was even using the glightbox-desc class..

```
<div class="glightbox-desc">
--
  | <a href="https://polyk3.test/"
  | class="button" ><i
  | class="fa fa-cart-plus"></i> Warenkorb hinzufügen</a>
  | </div>

```

**Comment by biati-digital** [comment]
Hi, please download the latest version, make sure the div with the description is outside your a tag, checkout the readme or the index.html for more information.
