### ISSUE TITLE
option to disable zoom?

### ISSUE THREAD

**Issue by carstengrimm** [biati-digital/glightbox#70]
couldn't find any information about that in the documentation.
do we have a parameter to disable zoom when clicking on an loaded image?

**Comment by biati-digital** [comment]
mmm... not yet, do you mean only for desktop? any specific reason to do this?

**Comment by bor-attila** [comment]
It's useful when ppl uses this script on individual images like in a restaurant's menu. I don't need the gallery function. User opens an image then he closes. With _afterSlideChange_ I solved closing the lightbox, but would be nice maybe a _onSlideClick_ event with 'zoom', 'close', 'none' or maybe a custom function options

**Comment by carstengrimm** [comment]
@biati-digital 
it's quite a difficult answer why we would need this...

if a viewer wants to check the source file and zoom in he could always call the jpg image url directly (open in new tab or whatever) so i wouldn't say the reason would be to deny accessing closer inspection of an image...

well let's say we have an image where zooming in is kinda a disadvantage (sloppy editing, retouching whatsoever) .. so it's would only limit on what you want/allow them to do...

**Comment by biati-digital** [comment]
Hi @carstengrimm not trying to be rude or anything but for me it sounds like **"not sure why we need this but we need this"**  the examples you mention seems like you are throwing ideas to give some validation to this feature request.

Not gonna implemente this (at least for now) and wait to see what other people think about this request.

In the meantime you can disable the Zoom with CSS:

```CSS
.gslide-image img.zoomable {
     pointer-events: none;
     cursor: default;
 }
```

@bor-attila it seems that the only thing you want is to close the Lightbox on slide click, for me the option you mention "onSlideClick" is a no go, the only use I can think of is for you to close the Lightbox but you can easily do that using the API already, each slide can have multiple types of content so an event to let you know the slide was clicked can hardly be useful, also with just 3 lines of code you can achieve what you want instead of adding that option that will require far more lines.

**Comment by robozb** [comment]
+1 option for disable zoom

**Comment by robozb** [comment]
With custome source this hack doesn't work:
pointer-events: none;
cursor: default;
