### ISSUE TITLE
Choosing opening position

### ISSUE THREAD

**Issue by TidyLuke** [biati-digital/glightbox#87]
**Describe the bug**
During my set up I define the gallery elements using the `elements` array. Everything works perfectly until I want to select the element to open on. I don't always want the lightbox to open on the first element. There are other factors which determine which slide should be showing when the lightbox is opened. As this is a changing starting position I can't define this in the opening settings, I've tried two ways which both cause the same issue (two images split in view, screenshots below)...

``` javascript
const options = {
	loop: true,
	onOpen: () => {
		lightbox.goToSlide(exampleNumber);
	},
};

const lightbox = GLightbox(options);
```

and 

``` javascript
const options = {
	loop: true,
};

const lightbox = GLightbox(options);

lightboxOpener.addEventListener('click', () => {
	lightbox.open();
	lightbox.goToSlide(exampleNumber);
});
```

**Are you able to reproduce the bug in the demo site**
No

**To Reproduce**
1. Set up GLightbox using the elements array
2. Have a trigger set to open the GLightbox
3. Try to open the Glightbox on any other item apart from the first

**Expected behavior**
I'd like to be able to open the lightbox on any number/position

**Screenshots**
https://imgur.com/3TzpwbF

**Comment by osroca** [comment]
Same issue here. I'm using the same approach as @TidyLuke to move the slider to the desired image when the Glightbox opens. I've even tried setting a low timeout to call `goToSlide(x)` to delay a bit its call in case the animation calculation could be affecting, but I have the same issue.
I think it happens only when the images being loaded have not the same dimensions (width at least).

**Comment by TidyLuke** [comment]
Hello @biati-digital I'm just wondering if you're aware of any fixes to the issue mentioned above? Apart from this everything is great, so a big thank you is placed alongside this query!

**Comment by biati-digital** [comment]
Hi, I currently have a lot of work so I'm not gonna be able to take a look at this until the end of April.

**Comment by TidyLuke** [comment]
Thank you for the response, the project this is being used on is due to go live soon. I'll try to hack a solution until you get the time.

As prior mentioned, thanks for the time you have spent with this project, it's been very helpful!

@osroca Did you manage to find a solution?

**Comment by osroca** [comment]
No, I'm sorry, didn't find a solution for it.

**Comment by TidyLuke** [comment]
@osroca  No worries, thought I'd check :)

**Comment by lamplightdev** [comment]
To get the gallery to open to a specific item you can manually set the `startAt` option in the lightbox `settings`, before you open it. E.g. in a click handler:

```js
lightbox.settings.startAt = myChosenIndex;
lightbox.open()
```

**Comment by TidyLuke** [comment]
Perfect, thank you @lamplightdev

**Comment by GlassGruber** [comment]
Hei there, I'm facing the same issue visible in OP screenshot, screenshot below is from Glightbox demo site
![image](https://github.com/biati-digital/glightbox/assets/1172428/c0350f66-7cf2-450c-84d1-bb325b45650f)

This issue is reproducible on the demo website by using this in the console and opening any image in first gallery.

```js
// index 2 is arbitrary
lightbox.on('open', () => { lightbox.goToSlide(2) })
```

--

Below is my setup
I've implemented a very blunt index counter attached to the lightbox parent element with `data-index` attribute. 
Now when the lightbox is closed and reopened I want the gallery to reopen where it was.

this is my super basic setup

```js
const lightbox = GLightbox({
    touchNavigation: true,
    openEffect: 'fade',
    closeEffect: 'fade',
    slideEffect: 'fade',
});

lightbox.open();

lightbox.on('open', () => { 
    // myElement is defined elsewhere
    let index = myElement.dataset.index;
    lightbox.goToSlide(index);
});

lightbox.on('slide_changed', ({ current }) => {
  // myElement is defined elsewhere
  myElement.dataset.index = current.index;
});
```
When I open my lightbox gallery the very same issue is reproduced as screenshot above.

So how can `goToSlide()` be used with a default setup (simple element with `.glightbox` class ) gallery?

**Comment by GlassGruber** [comment]
> This solution doesn't work for you? [#87 (comment)](https://github.com/biati-digital/glightbox/issues/87#issuecomment-599142634)

Unfortunately no, because I have a very basic setup as stated above, and delegated the entire open mechanism to default library behavior, I do not control how it is opened so all event bindings and clicks are (I think) what the library do and attach on its own.

The `lightbox.open();` command in my setup script is just because I want the gallery to be opened automatically when the page is accessed by the user.

**Comment by GlassGruber** [comment]
Gah, I found a workaround and pretty trivial too (thanks to you I have put my nose in that `startAt` setting again!).

Here is the edit, basically instead of writing it to an element data attribute I just modify on the fly the object start property, so that it will open the next time where it was and let the library do the rest without me having to state via explicit methods like `openAt` or `goToSlide`. 

```js
lightbox.on('slide_changed', ({ current }) => {
  ightbox.settings.startAt = current.index;
});
```

I guess this is an effective workaround, but the original issue is still present. 
Then again the v4 rewrite is in progress, so by using `startAt` with a timed event we can call it a day.
